# mount data source

In [7]:

from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


# import data


In [ ]:
import pandas as pd
# read the csv file
df_raw = pd.read_csv('/content/drive/MyDrive/data/sdp2022/task1_train_dataset.csv')
  
# display dataset
print(df_raw)

       index                                              title  \
0          0  Activation of nitrofurazone by azoreductases: ...   
1          1  Organisation and delivery of home care re-able...   
2          2  Relationships between anthocyanins and other c...   
3          3  New Insights into the Mechanisms of Water-Stre...   
4          4  Extensive chordate and annelid macrosynteny re...   
...      ...                                                ...   
51555  51555  BALB/c mice deficient in CD4(+) T cell IL-4R a...   
51556  51556         The Afterlife of Parliamentary Sovereignty   
51557  51557  Metabolomic Profiling of In Vivo Plasma Respons...   
51558  51558  Constant flux relation for diffusion-limited c...   
51559  51559  Sequence determinants for the tandem recogniti...   

            first_author                                        description  \
0            M Nakanishi                                                NaN   
1                  Allen             

In [ ]:
df = df_raw.copy()
df

index                                              title  \
0          0  Activation of nitrofurazone by azoreductases: ...   
1          1  Organisation and delivery of home care re-able...   
2          2  Relationships between anthocyanins and other c...   
3          3  New Insights into the Mechanisms of Water-Stre...   
4          4  Extensive chordate and annelid macrosynteny re...   
...      ...                                                ...   
51555  51555  BALB/c mice deficient in CD4(+) T cell IL-4R a...   
51556  51556         The Afterlife of Parliamentary Sovereignty   
51557  51557  Metabolomic Profiling of In Vivo Plasma Respons...   
51558  51558  Constant flux relation for diffusion-limited c...   
51559  51559  Sequence determinants for the tandem recogniti...   

            first_author                                        description  \
0            M Nakanishi                                                NaN   
1                  Allen                                                NaN   
2        Aurélie Bechoff                                                NaN   
3             H. Cochard                                                NaN   
4       Hui, Jerome H.L.  Genes with the homeobox motif are crucial in d...   
...                  ...                                                ...   
51555    Bryson Karen J.                                                NaN   
51556         Barber, NW                                                NaN   
51557  O'Kane, Anthony A                                                NaN   
51558  Connaughton, Colm  In a non-equilibrium system, a Constant Flux R...   
51559       John Edwards                                                NaN   

         core_id                               doi  pub_year  \
0      190682983                 10.1038/srep00063      2011   
1      403149987  10.1111/j.1365-2524.2011.01010.x      2011   
2      247875062    10.1016/j.foodchem.2013.09.132      2013   
3      253594132             10.1104/pp.109.138305      2009   
4       15139448             10.1093/molbev/msr175      2012   
...          ...                               ...       ...   
51555  204005191      10.1371/journal.pntd.0000930      2011   
51556   77380845               10.1093/icon/mor023      2011   
51557   16499864                 10.1021/es305345u      2013   
51558    2002669        10.1103/PhysRevE.78.041403      2008   
51559  204175263                10.1093/nar/gkr510      2011   

                                                   theme  
0      Allied Health Professions, Dentistry, Nursing ...  
1                          Social Work and Social Policy  
2               Agriculture, Veterinary and Food Science  
3               Earth Systems and Environmental Sciences  
4                                    Biological Sciences  
...                                                  ...  
51555  Allied Health Professions, Dentistry, Nursing ...  
51556                                                Law  
51557           Agriculture, Veterinary and Food Science  
51558                              Mathematical Sciences  
51559  Allied Health Professions, Dentistry, Nursing ...  

[51560 rows x 8 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51560 entries, 0 to 51559
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   index         51560 non-null  int64 
 1   title         51560 non-null  object
 2   first_author  51553 non-null  object
 3   description   16382 non-null  object
 4   core_id       51560 non-null  int64 
 5   doi           51560 non-null  object
 6   pub_year      51560 non-null  int64 
 7   theme         51560 non-null  object
dtypes: int64(3), object(5)
memory usage: 3.1+ MB


# select multiple columns from a dataframe

In [ ]:
df_Title_Theme = df[['title','theme']]
df_Title_Theme

title  \
0      Activation of nitrofurazone by azoreductases: ...   
1      Organisation and delivery of home care re-able...   
2      Relationships between anthocyanins and other c...   
3      New Insights into the Mechanisms of Water-Stre...   
4      Extensive chordate and annelid macrosynteny re...   
...                                                  ...   
51555  BALB/c mice deficient in CD4(+) T cell IL-4R a...   
51556         The Afterlife of Parliamentary Sovereignty   
51557  Metabolomic Profiling of In Vivo Plasma Respons...   
51558  Constant flux relation for diffusion-limited c...   
51559  Sequence determinants for the tandem recogniti...   

                                                   theme  
0      Allied Health Professions, Dentistry, Nursing ...  
1                          Social Work and Social Policy  
2               Agriculture, Veterinary and Food Science  
3               Earth Systems and Environmental Sciences  
4                                    Biological Sciences  
...                                                  ...  
51555  Allied Health Professions, Dentistry, Nursing ...  
51556                                                Law  
51557           Agriculture, Veterinary and Food Science  
51558                              Mathematical Sciences  
51559  Allied Health Professions, Dentistry, Nursing ...  

[51560 rows x 2 columns]

In [ ]:
df_2_4 = df.iloc[:, 1:3]
df_2_4

title       first_author
0      Activation of nitrofurazone by azoreductases: ...        M Nakanishi
1      Organisation and delivery of home care re-able...              Allen
2      Relationships between anthocyanins and other c...    Aurélie Bechoff
3      New Insights into the Mechanisms of Water-Stre...         H. Cochard
4      Extensive chordate and annelid macrosynteny re...   Hui, Jerome H.L.
...                                                  ...                ...
51555  BALB/c mice deficient in CD4(+) T cell IL-4R a...    Bryson Karen J.
51556         The Afterlife of Parliamentary Sovereignty         Barber, NW
51557  Metabolomic Profiling of In Vivo Plasma Respons...  O'Kane, Anthony A
51558  Constant flux relation for diffusion-limited c...  Connaughton, Colm
51559  Sequence determinants for the tandem recogniti...       John Edwards

[51560 rows x 2 columns]

In [ ]:
df_2to5 = df[df.columns[2:5]]
df_2to5

first_author                                        description  \
0            M Nakanishi                                                NaN   
1                  Allen                                                NaN   
2        Aurélie Bechoff                                                NaN   
3             H. Cochard                                                NaN   
4       Hui, Jerome H.L.  Genes with the homeobox motif are crucial in d...   
...                  ...                                                ...   
51555    Bryson Karen J.                                                NaN   
51556         Barber, NW                                                NaN   
51557  O'Kane, Anthony A                                                NaN   
51558  Connaughton, Colm  In a non-equilibrium system, a Constant Flux R...   
51559       John Edwards                                                NaN   

         core_id  
0      190682983  
1      403149987  
2      247875062  
3      253594132  
4       15139448  
...          ...  
51555  204005191  
51556   77380845  
51557   16499864  
51558    2002669  
51559  204175263  

[51560 rows x 3 columns]

first_author                                        description  \
0            M Nakanishi                                                NaN   
1                  Allen                                                NaN   
2        Aurélie Bechoff                                                NaN   
3             H. Cochard                                                NaN   
4       Hui, Jerome H.L.  Genes with the homeobox motif are crucial in d...   
...                  ...                                                ...   
51555    Bryson Karen J.                                                NaN   
51556         Barber, NW                                                NaN   
51557  O'Kane, Anthony A                                                NaN   
51558  Connaughton, Colm  In a non-equilibrium system, a Constant Flux R...   
51559       John Edwards                                                NaN   

         core_id  
0      190682983  
1      403149987  
2      247875062  
3      253594132  
4       15139448  
...          ...  
51555  204005191  
51556   77380845  
51557   16499864  
51558    2002669  
51559  204175263  

[51560 rows x 3 columns]

# series, dataframe, and ndarray

In [ ]:
# df['A']: type is Series

print(df_raw['pub_year'])
print("type of df_raw['pub_year']:", type(df_raw['pub_year']) )

0        2011
1        2011
2        2013
3        2009
4        2012
         ... 
51555    2011
51556    2011
51557    2013
51558    2008
51559    2011
Name: pub_year, Length: 51560, dtype: int64
type of df_raw['pub_year']: <class 'pandas.core.series.Series'>


In [ ]:
# df_raw[['pub_year']], type is DataFrame

print(df_raw[['pub_year']])
print("type of df_raw[['pub_year']]:", type(df_raw[['pub_year']]) )

       pub_year
0          2011
1          2011
2          2013
3          2009
4          2012
...         ...
51555      2011
51556      2011
51557      2013
51558      2008
51559      2011

[51560 rows x 1 columns]
type of df_raw[['pub_year']]: <class 'pandas.core.frame.DataFrame'>


In [ ]:
# df_raw['pub_year'].values, type is ndarray

print(df_raw['pub_year'].values)

print("type of df_raw['pub_year'].values:", type(df_raw['pub_year'].values))

[2011 2011 2013 ... 2013 2008 2011]
type of df_raw['pub_year'].values: <class 'numpy.ndarray'>


In [ ]:
# length of a ndarray

len(df_raw['pub_year'].values)

51560

In [ ]:
# length of series
len(df_raw['pub_year'])

51560

In [ ]:
# length of dataframe
len(df_raw[['pub_year']])

51560

# df['column1'].values vs df['column1'].toarray() X


In [ ]:
df['pub_year'].values

array([2011, 2011, 2013, ..., 2013, 2008, 2011])

In [ ]:
# 'Series' object has no attribute 'toarray' 
df['pub_year'].toarray()

AttributeError: ignored

In [ ]:
list(df['pub_year'])

In [ ]:
list(df['pub_year']).toarray()

AttributeError: ignored

In [ ]:
import numpy as np
np.array(df['pub_year'])

array([2011, 2011, 2013, ..., 2013, 2008, 2011])

# change data type in a column


In [ ]:
df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51560 entries, 0 to 51559
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype   
---  ------        --------------  -----   
 0   index         51560 non-null  int64   
 1   title         51560 non-null  object  
 2   first_author  51553 non-null  object  
 3   description   16382 non-null  object  
 4   core_id       51560 non-null  int64   
 5   doi           51560 non-null  object  
 6   pub_year      51560 non-null  int64   
 7   theme         51560 non-null  category
 8   theme_id      51560 non-null  int8    
dtypes: category(1), int64(3), int8(1), object(4)
memory usage: 2.9+ MB


from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(stop_words='english')

description = df['tokens'].astype(str)

dtm  = tfidf.fit_transform(description) 

dtm = pd.DataFrame(dtm.todense(), columns = tfidf.get_feature_names())

dtm.head()

In [ ]:
# .astype（）
df['pub_year_str'] = df['pub_year'].astype(str)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51560 entries, 0 to 51559
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype   
---  ------        --------------  -----   
 0   index         51560 non-null  int64   
 1   title         51560 non-null  object  
 2   first_author  51553 non-null  object  
 3   description   16382 non-null  object  
 4   core_id       51560 non-null  int64   
 5   doi           51560 non-null  object  
 6   pub_year      51560 non-null  int64   
 7   theme         51560 non-null  category
 8   theme_id      51560 non-null  int8    
 9   pub_year_str  51560 non-null  object  
dtypes: category(1), int64(3), int8(1), object(5)
memory usage: 3.2+ MB


# encode features into categories
encode text/string feature




In [ ]:
# approach 1: 
# df['column1'].astype('category')
# df['column1'].cat.codes

df["theme"] = df["theme"].astype('category')
df.dtypes
print('df.dtypes is', df.dtypes)

df["theme_id"] = df["theme"].cat.codes
df.head(3)

df.dtypes is index              int64
title             object
first_author      object
description       object
core_id            int64
doi               object
pub_year           int64
theme           category
dtype: object


index                                              title     first_author  \
0      0  Activation of nitrofurazone by azoreductases: ...      M Nakanishi   
1      1  Organisation and delivery of home care re-able...            Allen   
2      2  Relationships between anthocyanins and other c...  Aurélie Bechoff   

  description    core_id                               doi  pub_year  \
0         NaN  190682983                 10.1038/srep00063      2011   
1         NaN  403149987  10.1111/j.1365-2524.2011.01010.x      2011   
2         NaN  247875062    10.1016/j.foodchem.2013.09.132      2013   

                                               theme  theme_id  
0  Allied Health Professions, Dentistry, Nursing ...         2  
1                      Social Work and Social Policy        32  
2           Agriculture, Veterinary and Food Science         1

# which encoders to use

- 当分类变量存在顺序关系（有序变量）时，如【小学，初中，高中】，可以使用 `sklearn.preprocessing.OrdinalEncoder` 进行编码

- 当分类变量不存在顺序关系时，如【红，黄，蓝，绿】，可以使用 `sklearn.preprocessing.OneHotEncoder` 进行编码



#fit encoder into dataframe and columns

In [ ]:
from sklearn.preprocessing import OrdinalEncoder
# 创建一个OrdinalEncoder 对象(实例) object， 用来对特征进行编码
oe = OrdinalEncoder()

# 编码器实例创建好了
# how to apply to a dataframe['column']? 
# can it fit into a dataframe, an array, or a series?

In [ ]:
# fit into an array, this doesn't work
# oe = oe.fit(df_raw['pub_year'].values)


In [ ]:
df.head(2)

index                                              title first_author  \
0      0  Activation of nitrofurazone by azoreductases: ...  M Nakanishi   
1      1  Organisation and delivery of home care re-able...        Allen   

  description    core_id                               doi  pub_year  \
0         NaN  190682983                 10.1038/srep00063      2011   
1         NaN  403149987  10.1111/j.1365-2524.2011.01010.x      2011   

                                               theme  theme_id pub_year_str  
0  Allied Health Professions, Dentistry, Nursing ...         2         2011  
1                      Social Work and Social Policy        32         2011

In [ ]:
# copy a column to a new column
df['pub_year_copy'] = df['pub_year']
df.head(2)

index                                              title first_author  \
0      0  Activation of nitrofurazone by azoreductases: ...  M Nakanishi   
1      1  Organisation and delivery of home care re-able...        Allen   

  description    core_id                               doi  pub_year  \
0         NaN  190682983                 10.1038/srep00063      2011   
1         NaN  403149987  10.1111/j.1365-2524.2011.01010.x      2011   

                                               theme  theme_id  pub_year_copy  
0  Allied Health Professions, Dentistry, Nursing ...         2           2011  
1                      Social Work and Social Policy        32           2011

In [ ]:
# approach 1, does not work
df['pub_year_copy'].apply(oe().fit_transform)


TypeError: ignored

In [ ]:
# approach 2, does not work
oe.fit_transform(df['pub_year_copy'])


ValueError: ignored

In [ ]:
oe.fit_transform(df['pub_year_copy'].values)

ValueError: ignored

In [ ]:
oe.fit_transform(df['pub_year_copy'].values.reshape(-1,1))
# it finally works

array([[4.],
       [4.],
       [6.],
       ...,
       [6.],
       [1.],
       [4.]])

In [ ]:
oe.fit_transform(df['pub_year_copy'].values.reshape(-1,1)).shape

(51560, 1)

In [ ]:
len(oe.fit_transform(df['pub_year_copy'].values.reshape(-1,1)))

51560

In [ ]:
oe.fit_transform(df['pub_year_copy'].values.reshape(-1,1)).shape

(51560, 1)

In [ ]:
array1 = oe.fit_transform(df['pub_year_copy'].values.reshape(-1,1))
array1[1]

array([4.])

In [ ]:
type(array1[1])

numpy.ndarray

In [ ]:
array1[1].shape

(1,)

In [ ]:
import numpy as np
a = np.array([1,2,3,4]) #this form produced a bug
a.shape 

(4,)

In [ ]:
# converting your 1D array to 2D:
a.shape = [4,1]


In [ ]:
a

array([[1],
       [2],
       [3],
       [4]])

In [ ]:
# convert 2D array to 1D
a = np.array([[1,2,3], [4,5,6]])
b=a.reshape(-1)
b

array([1, 2, 3, 4, 5, 6])

In [ ]:
array1[1][0]

4.0

# corret fit 

In [ ]:
# fit into a dataframe
oe2 = oe.fit_transform(df[['pub_year_copy']])

In [ ]:
oe2

array([[4.],
       [4.],
       [6.],
       ...,
       [6.],
       [1.],
       [4.]])

In [ ]:
df['pub_year_copy_fitted'] = oe.fit_transform(df[['pub_year_copy']])

In [ ]:
df

index                                              title  \
0          0  Activation of nitrofurazone by azoreductases: ...   
1          1  Organisation and delivery of home care re-able...   
2          2  Relationships between anthocyanins and other c...   
3          3  New Insights into the Mechanisms of Water-Stre...   
4          4  Extensive chordate and annelid macrosynteny re...   
...      ...                                                ...   
51555  51555  BALB/c mice deficient in CD4(+) T cell IL-4R a...   
51556  51556         The Afterlife of Parliamentary Sovereignty   
51557  51557  Metabolomic Profiling of In Vivo Plasma Respons...   
51558  51558  Constant flux relation for diffusion-limited c...   
51559  51559  Sequence determinants for the tandem recogniti...   

            first_author                                        description  \
0            M Nakanishi                                                NaN   
1                  Allen                                                NaN   
2        Aurélie Bechoff                                                NaN   
3             H. Cochard                                                NaN   
4       Hui, Jerome H.L.  Genes with the homeobox motif are crucial in d...   
...                  ...                                                ...   
51555    Bryson Karen J.                                                NaN   
51556         Barber, NW                                                NaN   
51557  O'Kane, Anthony A                                                NaN   
51558  Connaughton, Colm  In a non-equilibrium system, a Constant Flux R...   
51559       John Edwards                                                NaN   

         core_id                               doi  pub_year  \
0      190682983                 10.1038/srep00063      2011   
1      403149987  10.1111/j.1365-2524.2011.01010.x      2011   
2      247875062    10.1016/j.foodchem.2013.09.132      2013   
3      253594132             10.1104/pp.109.138305      2009   
4       15139448             10.1093/molbev/msr175      2012   
...          ...                               ...       ...   
51555  204005191      10.1371/journal.pntd.0000930      2011   
51556   77380845               10.1093/icon/mor023      2011   
51557   16499864                 10.1021/es305345u      2013   
51558    2002669        10.1103/PhysRevE.78.041403      2008   
51559  204175263                10.1093/nar/gkr510      2011   

                                                   theme  theme_id  \
0      Allied Health Professions, Dentistry, Nursing ...         2   
1                          Social Work and Social Policy        32   
2               Agriculture, Veterinary and Food Science         1   
3               Earth Systems and Environmental Sciences        15   
4                                    Biological Sciences         7   
...                                                  ...       ...   
51555  Allied Health Professions, Dentistry, Nursing ...         2   
51556                                                Law        23   
51557           Agriculture, Veterinary and Food Science         1   
51558                              Mathematical Sciences        24   
51559  Allied Health Professions, Dentistry, Nursing ...         2   

       pub_year_copy  pub_year_copy_fitted  
0               2011                   4.0  
1               2011                   4.0  
2               2013                   6.0  
3               2009                   2.0  
4               2012                   5.0  
...              ...                   ...  
51555           2011                   4.0  
51556           2011                   4.0  
51557           2013                   6.0  
51558           2008                   1.0  
51559           2011                   4.0  

[51560 rows x 11 columns]

In [ ]:

oe.categories_

[array([2007, 2008, 2009, 2010, 2011, 2012, 2013])]

In [ ]:
# .astype('category') approach

In [ ]:
df["pub_year_category"] = df["pub_year_copy"].astype('category')
df.dtypes
print('df.dtypes is', df.dtypes)



df.dtypes is index                      int64
title                     object
first_author              object
description               object
core_id                    int64
doi                       object
pub_year                   int64
theme                   category
theme_id                    int8
pub_year_copy              int64
pub_year_copy_fitted     float64
pub_year_category       category
dtype: object


In [ ]:
df

index                                              title  \
0          0  Activation of nitrofurazone by azoreductases: ...   
1          1  Organisation and delivery of home care re-able...   
2          2  Relationships between anthocyanins and other c...   
3          3  New Insights into the Mechanisms of Water-Stre...   
4          4  Extensive chordate and annelid macrosynteny re...   
...      ...                                                ...   
51555  51555  BALB/c mice deficient in CD4(+) T cell IL-4R a...   
51556  51556         The Afterlife of Parliamentary Sovereignty   
51557  51557  Metabolomic Profiling of In Vivo Plasma Respons...   
51558  51558  Constant flux relation for diffusion-limited c...   
51559  51559  Sequence determinants for the tandem recogniti...   

            first_author                                        description  \
0            M Nakanishi                                                NaN   
1                  Allen                                                NaN   
2        Aurélie Bechoff                                                NaN   
3             H. Cochard                                                NaN   
4       Hui, Jerome H.L.  Genes with the homeobox motif are crucial in d...   
...                  ...                                                ...   
51555    Bryson Karen J.                                                NaN   
51556         Barber, NW                                                NaN   
51557  O'Kane, Anthony A                                                NaN   
51558  Connaughton, Colm  In a non-equilibrium system, a Constant Flux R...   
51559       John Edwards                                                NaN   

         core_id                               doi  pub_year  \
0      190682983                 10.1038/srep00063      2011   
1      403149987  10.1111/j.1365-2524.2011.01010.x      2011   
2      247875062    10.1016/j.foodchem.2013.09.132      2013   
3      253594132             10.1104/pp.109.138305      2009   
4       15139448             10.1093/molbev/msr175      2012   
...          ...                               ...       ...   
51555  204005191      10.1371/journal.pntd.0000930      2011   
51556   77380845               10.1093/icon/mor023      2011   
51557   16499864                 10.1021/es305345u      2013   
51558    2002669        10.1103/PhysRevE.78.041403      2008   
51559  204175263                10.1093/nar/gkr510      2011   

                                                   theme  theme_id  \
0      Allied Health Professions, Dentistry, Nursing ...         2   
1                          Social Work and Social Policy        32   
2               Agriculture, Veterinary and Food Science         1   
3               Earth Systems and Environmental Sciences        15   
4                                    Biological Sciences         7   
...                                                  ...       ...   
51555  Allied Health Professions, Dentistry, Nursing ...         2   
51556                                                Law        23   
51557           Agriculture, Veterinary and Food Science         1   
51558                              Mathematical Sciences        24   
51559  Allied Health Professions, Dentistry, Nursing ...         2   

       pub_year_copy  pub_year_copy_fitted pub_year_category  
0               2011                   4.0              2011  
1               2011                   4.0              2011  
2               2013                   6.0              2013  
3               2009                   2.0              2009  
4               2012                   5.0              2012  
...              ...                   ...               ...  
51555           2011                   4.0              2011  
51556           2011                   4.0              2011  
51557           2013                   6.0              2013  
51558        

In [ ]:
df["pub_year_category_id"] = df["pub_year_category"].cat.codes
df.head(10)

index                                              title      first_author  \
0      0  Activation of nitrofurazone by azoreductases: ...       M Nakanishi   
1      1  Organisation and delivery of home care re-able...             Allen   
2      2  Relationships between anthocyanins and other c...   Aurélie Bechoff   
3      3  New Insights into the Mechanisms of Water-Stre...        H. Cochard   
4      4  Extensive chordate and annelid macrosynteny re...  Hui, Jerome H.L.   
5      5  Generation of N-ethyl-N-nitrosourea-induced mo...  Aigner, Bernhard   
6      6  A useful approach to identify novel small-mole...      Kenneth Ewan   
7      7  The influence of Tall Man lettering on drug na...        Ruth Filik   
8      8  Modulation of Fgfr1a Signaling in Zebrafish Re...    Norton, W.H.J.   
9      9       Democratic limits to preventive criminal law     Ramsay, Peter   

                                         description    core_id  \
0                                                NaN  190682983   
1                                                NaN  403149987   
2                                                NaN  247875062   
3                                                NaN  253594132   
4  Genes with the homeobox motif are crucial in d...   15139448   
5                                                NaN    2777437   
6                                                NaN  282869015   
7                                                NaN  356891313   
8  Behavioral syndromes are suites of two or more...  214684259   
9  Recent criminal legislation has been character...    9694982   

                                         doi  pub_year  \
0                          10.1038/srep00063      2011   
1           10.1111/j.1365-2524.2011.01010.x      2011   
2             10.1016/j.foodchem.2013.09.132      2013   
3                      10.1104/pp.109.138305      2009   
4                      10.1093/molbev/msr175      2012   
5             10.1113/expphysiol.2008.045864      2009   
6              10.1158/0008-5472.CAN-10-1028      2010   
7           10.2165/11532360-000000000-00000      2010   
8             10.1523/JNEUROSCI.2892-11.2011      2011   
9  10.1093/acprof:oso/9780199656769.003.0012      2013   

                                               theme  theme_id  pub_year_copy  \
0  Allied Health Professions, Dentistry, Nursing ...         2           2011   
1                      Social Work and Social Policy        32           2011   
2           Agriculture, Veterinary and Food Science         1           2013   
3           Earth Systems and Environmental Sciences        15           2009   
4                                Biological Sciences         7           2012   
5                                Biological Sciences         7           2009   
6                                Biological Sciences         7           2010   
7       Art and Design: History, Practice and Theory         6           2010   
8            Psychology, Psychiatry and Neuroscience        30           2011   
9                                                Law        23           2013   

   pub_year_copy_fitted pub_year_category  pub_year_category_id  
0                   4.0              2011                     4  
1                   4.0              2011                     4  
2                   6.0              2013                     6  
3                   2.0              2009                     2  
4                   5.0              2012                     5  
5                   2.0              2009                     2  
6                   3.0              2010                     3  
7                   3.0              2010                     3  
8                   4.0              2011                     4  
9                   6.0              2013                     6

# difference between python list and numpy array

In [ ]:
import numpy as np 

list_a=[2,3,4]
array_a = np.array(list_a)
array_a

array([2, 3, 4])

# numpy array reshape: reshape(-1,1)

In [ ]:
# Unknown Dimension
# Pass -1 as the value, and NumPy will calculate this number of this dimension for you.

array.reshape(-1, 1) 

# flatten a nested list

In [ ]:
import numpy as np
flatten_list = list(np.concatenate(list1).flat)
flatten_list

In [ ]:
flat_list = []
for row in list1:
    for x in row:
        flat_list.append(x)

flat_list       

In [ ]:
flat_list1 = [x for row in list1 for x in row]
flat_list1

In [ ]:

arr = []
for row in list1:
  for j in row: 
    arr.append(j)

arr

In [ ]:
# or as a function
def flatten(xss):
    return [x for xs in xss for x in xs]

# fit vs fit_transform 

In [ ]:
# fit into a dataframe
df['new_column'] = oe.fit_transform(df[['pub_year_copy']])

In [ ]:
df

In [ ]:
#python - How to use sklearn fit_transform with pandas and return dataframe instead of numpy array? - Stack Overflow
#https://stackoverflow.com/questions/35723472/how-to-use-sklearn-fit-transform-with-pandas-and-return-dataframe-instead-of-num

# columns = ["col1", "col2", "col3", "col4"]
#autoscaler = StandardScaler()
# df[columns] = autoscaler.fit_transform(df[columns])

In [ ]:
df_raw['pub_year_oe2']= oe.fit_transform(df_raw[['pub_year']])

In [ ]:
df_raw.head(2)

In [ ]:
# the redundant way

In [ ]:
oe3 = OrdinalEncoder()

# create a new dataframe
df_fit_trans = pd.DataFrame(oe3.fit_transform(df_raw[['pub_year']]), columns=['pub_year_new'])
df_fit_trans
# ref: 
# python - How can I convert the StandardScaler() transformation back to dataframe? - Stack Overflow
# https://stackoverflow.com/questions/64161419/how-can-i-convert-the-standardscaler-transformation-back-to-dataframe

In [ ]:
oe1 = OrdinalEncoder()
df_raw['pub_year_fit'] = oe1.fit(df_raw[['pub_year']])

In [ ]:

df_raw['pub_year_fit_transform'] = oe1.transform(df_raw[['pub_year']])

In [ ]:
df_raw.head(3)

In [ ]:
df_raw.info()

In [ ]:
oe.categories_


[array([2007, 2008, 2009, 2010, 2011, 2012, 2013])]

In [ ]:
# display unique values

print('column values:' , df_raw['pub_year_transformed'].unique())
print('unique values: ', df_raw['pub_year_transformed'].unique().tolist())

In [ ]:
type(df_raw['pub_year_transformed'].unique())

In [ ]:
type(df_raw['pub_year_transformed'].unique().tolist())

In [ ]:
# count how many unique values

df_raw['pub_year_transformed'].nunique()

In [ ]:
# count values of each categoriy

In [ ]:
df_raw['pub_year_transformed'].value_counts()

In [ ]:
data_.iloc[:,1,-1] = oe.transform(data.iloc[:,1,-1])

In [ ]:

oe = oe.fit(df_raw.pub_year)

In [ ]:
df["theme"] = df["theme"].astype('category')
df.dtypes

df["theme_id"] = df["theme"].cat.codes
df.tail()

In [ ]:
df_raw.info()

In [ ]:
df_

# how many kind of encoders 

In [ ]:
# LabelEncoder # for label 
# sklearn.preprocessing.OneHotEncoder # for feature 
# sklearn.preprocessing.OrdinalEncoder # for feature

# 为一个列表构建词典

In [ ]:
src = ["red", "blue", "green", "red", "red", "blue", "yellow"]
color_dict = dict()
for i in range(len(src)):
  k = src[i]  # like "red"
  if k not in color_dict:
    color_dict[k] = len(color_dict)
print(color_dict)

{'red': 0, 'blue': 1, 'green': 2, 'yellow': 3}



## 查看类别分布

In [ ]:
# code format

count_class = pd.value_counts(df['theme'],sort = True).sort_index()

# ref
# scikit-learn 逻辑回归实现信用卡欺诈检测 - PythonTechWorld
# https://pythontechworld.com/article/detail/NL9JP9r2Djun


In [ ]:
count_class

Aeronautical, Mechanical, Chemical and Manufacturing Engineering                 1243
Agriculture, Veterinary and Food Science                                         1352
Allied Health Professions, Dentistry, Nursing and Pharmacy                       3602
Anthropology and Development Studies                                              457
Architecture, Built Environment and Planning                                      896
Area Studies                                                                      269
Art and Design: History, Practice and Theory                                      412
Biological Sciences                                                              3026
Business and Management Studies                                                  3906
Chemistry                                                                        1597
Civil and Construction Engineering                                                472
Classics                                              